<?php 
include('whatappicon.php');
include('header.php');
include('carousel.php');
include('historia.php');
include('diferenciais.php');
include('servicos.php');
include('cta.php');
include('frota.php');
include('contato.php');
include('footer.php')
?>